import './globals.css'
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primereact/resources/primereact.min.css";
import RootLayout from '@/components/layouts/RootLayout';

// TODO gérer les metadata
// export const metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// }

export default function AppLayout({ children }) {

    return (
        <RootLayout>
            {children}
        </RootLayout>
    )
}